### ISSUE TITLE
Error on dep ensure

### ISSUE THREAD

**Issue by ilya-lt** [acrazing/cheapjson#2]
I get this error:
Solving failure: No versions of github.com/acrazing/cheapjson met constraints:
	master: unexpected error while defensively cleaning up after possible derelict nested submodule directories: fatal: No url found for submodule path 'json-test-suite' in .gitmodules
: command failed: [git submodule foreach --recursive git clean -x -d -f -f]: exit status 128

when trying to run _dep ensure_ on a project with this as dependency.

golang version is 1.12.10
dep version is 0.5.4

installing via go get works, but it would be nice not to have to run manual commands besides dep ensure.

**Comment by acrazing** [comment]
I'm so sorry for it and it is fine now.

**Comment by ilya-lt** [comment]
thank you, I'll verify in a couple of hours.
